// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/triage/ingest": {
            "post": {
                "description": "Recibe datos y devuelve el QR generado (Imagen + Texto)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Triage"
                ],
                "summary": "Generar QR",
                "parameters": [
                    {
                        "description": "Datos",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.IngestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.IngestResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.IngestRequest": {
            "type": "object",
            "properties": {
                "studentId": {
                    "type": "string",
                    "example": "EST-SWAGGER-01"
                },
                "symptoms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "dolor",
                        " mareo"
                    ]
                }
            }
        },
        "main.IngestResponse": {
            "type": "object",
            "properties": {
                "appointmentId": {
                    "type": "string",
                    "example": "550e8400..."
                },
                "message": {
                    "type": "string",
                    "example": "Procesado Correctamente"
                },
                "qr_data": {
                    "type": "string",
                    "example": "DERMA|EST|UUID"
                },
                "qr_image": {
                    "type": "string",
                    "example": "data:image/png;base64..."
                },
                "status": {
                    "type": "string",
                    "example": "SUCCESS"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3006",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "DermaTech Triage API",
	Description:      "Microservicio de Ingesta (Lineal)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
