import { ApiProperty } from '@nestjs/swagger';

/**
 * Event Contract: Defines the data payload sent over Kafka when a user registers.
 * This ensures Auth Service (Producer) and Patient Service (Consumer) speak the same language.
 */
export class UserRegisteredEvent {
  
  @ApiProperty({ 
    description: 'Unique User ID generated by Auth Service (The Key Link)', 
    example: 'd8139c6f-a928-4b71-aa84-a51da3fbae34' 
  })
  public readonly userId: string;

  @ApiProperty({ 
    description: 'Institutional email address', 
    example: 'student@uce.edu.ec' 
  })
  public readonly email: string;

  @ApiProperty({ 
    description: 'Assigned system role', 
    example: 'STUDENT' 
  })
  public readonly role: string;

  constructor(userId: string, email: string, role: string) {
    this.userId = userId;
    this.email = email;
    this.role = role;
  }

  /**
   * Helper to ensure the event payload is serialized as a clean JSON string.
   */
  toString(): string {
    return JSON.stringify({
      userId: this.userId,
      email: this.email,
      role: this.role,
    });
  }
}