name: "05. SMOKE TEST QA"

on:
  workflow_dispatch:
  #workflow_run:
    #workflows: ["03. BACKEND QA", "04. FRONTEND QA"]
    #types:
      #- completed

jobs:
  load-testing:
    name: 🧪 QA Smoke Test (Dominios Reales)
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Execute k6 Load Test against QA Domain
        uses: grafana/k6-action@v0.3.0
        env:
          API_URL: "http://martharodriguez_qa2.distribuidauce.org"
        with:
          filename: tests/load/smoke-test.js
          flags: --env API_URL="http://martharodriguez_qa2.distribuidauce.org"